spring:
  application:
    name: pgerator


logging:
  level:
    no.fintlabs: debug

fint:
  aiven:
    token:
    base-url: https://api.aiven.io/v1
    project: fintlabs
    service:

management:
  endpoints:
    web:
      exposure:
        include: "*"