apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pgerator
  labels:
    app.kubernetes.io/name: fint-pgerator
    app.kubernetes.io/instance: pgerator
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: GA
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: fintlabs-application-infrastructure-services
    fintlabs.no/team: flais
spec:
  itemPath: "vaults/aks-api-vault/items/pgerator"