kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgerator
subjects:
- kind: ServiceAccount
  name: pgerator
  namespace: operators
roleRef:
  kind: ClusterRole
  name: pgerator
  apiGroup: rbac.authorization.k8s.io